
before_build:
 - nuget restore
build_script:
 - msbuild /verbosity:quiet "FastMapper.sln"
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"FastMapper.UnitTest\bin\Debug\FastMapper.UnitTest.dll -noshadow" -output:"coverage.xml" -filter:"+[FastMapper.UnitTest*]* -[FastMapper.UnitTest*]*"
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t d93e8440-732b-4bef-9cf3-3476578be1b1